### PR TITLE
Update source file with joke change

### PR DESCRIPTION
**Pull request by zkat**
Related to #164 and #163, possibly supersedes it?

### CODE REVIEW

**Comment by jonschlinkert** [comment]
awesome, thank you!

**Comment by jdax** [comment]
Just here to say I like this PR. As someone who isn't a man and does not currently have the ability to grow a beard, this joke said to me that not-bearded people weren't welcome. Which leaves out a lot of people, most especially people who are women.

**Comment by jonschlinkert** [comment]
fwiw, the response to this joke has been surprising. this was the first website I created when I started learning how to program (and assemble was the first major javascript program I worked on). I remember seeing references to beards in programming books, and seeing companies with the word "beard" in the name, and it struck me as funny that programming culture had so much "beard-lore".  The joke was making fun of the beard stereotype, and it's intent was quite the opposite of how it's being interpreted. my wife is a programmer with a degree in electrical engineering. The joke, if anything, would have been more exclusionary to bearded males (which might explain why most of the 6 or 7 complaints were from bearded men). It would have never even occurred to me that others might think the joke was exclusionary to women. My apologies if it was taken that way.

**Comment by zkat** [comment]
Thanks a bunch! It's pretty clear it wasn't intended that way, and I used to make plenty of neckbeard jokes myself. The best strategy is definitely to listen when people bring it up and correct it -- it's literally impossible for us to know what words we use could hurt people, but doing stuff like this (asking for a PR, and apologizing for the oversight), is pretty much the ideal response.

**Comment by jdax** [comment]
++ to all this - probably one of the best responses to community concerns I've seen. A+

**Comment by jonschlinkert** [comment]
thanks! that means a lot to me!

**Pull request merged**
