### PR TITLE
Editorialize joke in About.html

### PR DESCRIPTION
**Pull request by zkat**
#163 asked for a PR to change this, so I figured I'd just submit one. There's already a joke here, so I tried to nudge that existing joke a little.

Cheers!

### CODE REVIEW

**Comment by jonschlinkert** [comment]
ha, nice. it's going in the right direction but I personally would rather not make jokes about drugs. especially pot, since it's just as likely to make bearded males feel as alienated as the existing joke ;) 

keep 'em coming!

**Comment by zkat** [comment]
Removed the drug reference. :)

**Comment by jonschlinkert** [comment]
thanks, would you mind making the change in source too?

**Comment by doowb** [comment]
The source can be found [on the master branch](https://github.com/assemble/assemble.io/blob/master/templates/pages/docs/About.md.hbs).

**Comment by jonschlinkert** [comment]
we can make the change on master if you're pressed for time. I like the changes

**Comment by zkat** [comment]
All done, see #165. lmk if there's anything else y'all need.

**Comment by jonschlinkert** [comment]
thanks! that was fast. consider the about page "shaven"

**Pull request merged**
